export const categories: { label: string, icon: string, description: string }[] = [
    { label: "Geography", icon: "location_on", description: "Questions about countries, cities, and landmarks." },
    { label: "History", icon: "fast_forward", description: "Questions about historical events and figures." },
    { label: "Generative AI", icon: "network_intelligence", description: "Questions about artificial intelligence and machine learning." },
    { label: "Chemistry", icon: "experiment", description: "Questions about chemical elements and reactions." },
    { label: "Biology", icon: "genetics", description: "Questions about living organisms and ecosystems." },
    { label: "Physics", icon: "biotech", description: "Questions about matter, energy, and forces." },
    { label: "Australia", icon: "flag", description: "Questions about Australia" },
    { label: "Food", icon: "ramen_dining", description: "Questions about food and cooking." },
    { label: "Music", icon: "music_note", description: "Questions about music and musicians." },
    { label: "Movies", icon: "movie", description: "Questions about movies and actors." },
    { label: "Books", icon: "library_books", description: "Questions about books and authors." },
    { label: "Art", icon: "palette", description: "Questions about art and artists." },
    { label: "Basketball", icon: "sports_basketball", description: "Questions about basketball." },
    { label: "Football", icon: "sports_football", description: "Questions about football." },
    { label: "Soccer", icon: "sports_soccer", description: "Questions about soccer." },
    { label: "Squash", icon: "sports_tennis", description: "Questions about the game squash." },
];